#!/usr/bin/env python
import argparse
import logging
from culmqtt.culmqtt import CULMQTT
import signal


def prepare_parser(parser):
    parser.add_argument(
        "-d",
        "--device",
        type=str,
        default="/dev/ttyUSB0",
        help="Port to of the CUL device",
    )
    parser.add_argument(
        "-b",
        "--broker",
        type=str,
        default="localhost",
        help="IP address of the MQTT broker",
    )
    parser.add_argument(
        "-P",
        "--port",
        type=str,
        default=None,
        help="TCP port of the MQTT broker",
    )
    parser.add_argument(
        "-t",
        "--topic",
        type=str,
        default="cul",
        help="MQTT topic for this CULT device",
    )
    parser.add_argument(
        "-i",
        "--clientid",
        type=str,
        default="cul",
        help="MQTT client ID"
    )
    parser.add_argument(
        "-u",
        "--username",
        type=str,
        default=None,
        help="MQTT broker user name (optional)",
    )
    parser.add_argument(
        "-p",
        "--password",
        type=str,
        default=None,
        help="MQTT broker password name (optional)",
    )
    parser.add_argument(
        "--tls",
        action="store_true",
        help="Connect to MQTT broker with TLS encryption",
    )
    parser.add_argument(
        "-c",
        "--ca-certs",
        type=str,
        default=None,
        help="Path to TLS certificates for MQTT broker connection",
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Allow insecure connection (no CA certificate validation)",
    )
    parser.add_argument(
        "-D",
        "--delayms",
        type=int,
        default=500,
        help="Delay after sending a message via CUL",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="Verbose or extra verbose (2x) logging",
    )


def run_program(parser):

    def stop_culmqtt(sig_num, frame):
        # stop event scheduler
        logger.warning(
            "CULmqtt was interrupted by signal '%s'",
            signal.Signals(sig_num).name
        )
        cul_mqtt.stop()
        logger.warning("CULmqtt has been stopped, bye...")
        exit(sig_num)

    config = vars(parser.parse_args())
    # prepare logging
    log_level = logging.ERROR
    if config["verbose"] and config["verbose"] == 1:
        log_level = logging.INFO
    elif config["verbose"] and config["verbose"] >= 2:
        log_level = logging.DEBUG
    logging.basicConfig(format="%(levelname)s : %(name)s : %(message)s",)
    logger = logging.getLogger("cul-mqtt")
    logger.setLevel(log_level)
    # run
    logger.debug("CLI arguments: %s", config)
    cul_mqtt = CULMQTT(
        config["device"],
        config["broker"],
        mqtt_port=config["port"],
        mqtt_client_id=config["clientid"],
        mqtt_topic=config["topic"],
        username=config["username"],
        password=config["password"],
        tls=config["tls"],
        ca_certs=config["ca_certs"],
        tls_insecure=config["insecure"],
        delay_send=config["delayms"] / 1000.0,
        log_level=log_level,
    )
    # Add signal handler to gracefully terminate cul_mqtt
    signal.signal(signal.SIGINT, stop_culmqtt)
    signal.signal(signal.SIGTERM, stop_culmqtt)
    cul_mqtt.start()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CUL to MQTT bridge.")
    prepare_parser(parser)
    run_program(parser)
